services:
  - type: web
    name: healthcare-cost-modeler
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd app && gunicorn app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0